
import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.*;

public class GUI extends javax.swing.JFrame {

    private DBManager dbmanager;

    /**
     * Creates new form GUI
     */
    public GUI(DBManager dbm) {
        initComponents();
        this.dbmanager = dbm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        uusiEtunimi = new javax.swing.JTextField();
        uusiSukunimi = new javax.swing.JTextField();
        uusiOsoite = new javax.swing.JTextField();
        uusiPuhelin = new javax.swing.JTextField();
        uusiSahkoposti = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        osoiteLabel = new javax.swing.JLabel();
        puhelinLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lisaaAsiakasOK = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        asiakasLista = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        etsittavaAsiakas = new javax.swing.JTextField();
        haeAsiakkaat = new javax.swing.JButton();
        kohteenTyyppi = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        kohteenOsoiteLabel = new javax.swing.JLabel();
        kohteenOsoite = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        erienLKM = new javax.swing.JComboBox<>();
        lisaaKohdeOK = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        onTarjous = new javax.swing.JCheckBox();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        etsittavaTarjous = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        haeTarjouksista = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tarjousLista = new javax.swing.JList<>();
        poistaTarjousStatus = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        etsittavaOsoite = new javax.swing.JTextField();
        haeKohdeOsoitteella = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        kohdeLista = new javax.swing.JList<>();
        jLabel11 = new javax.swing.JLabel();
        tuntityyppi = new javax.swing.JComboBox<>();
        tuntimaara = new javax.swing.JTextField();
        lisaaTuntejaOK = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        etsittavaTarvike = new javax.swing.JTextField();
        haeTarvikeNimella = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tarvikeLista = new javax.swing.JList<>();
        jLabel13 = new javax.swing.JLabel();
        tarvikemaara = new javax.swing.JTextField();
        lisaaTarvikeOK = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        kohdeSisaltaaTunnit = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        kohdeSisaltaaTarvikkeet = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        paattyvaEtsittavaOsoite = new javax.swing.JTextField();
        paattyvaEtsittavaAsiakas = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        paattyvaKohdeLista = new javax.swing.JList<>();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane7 = new javax.swing.JScrollPane();
        kohteenSisaltoTaulukko = new javax.swing.JTable();
        haePaattyvaKohdeOsoite = new javax.swing.JButton();
        haePaattyvaKohdeAsiakas = new javax.swing.JButton();
        luoLaskuOK = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        uusiTarvikeNimi = new javax.swing.JTextField();
        uusiYksikko = new javax.swing.JTextField();
        uusiVarastotilanne = new javax.swing.JTextField();
        uusiOstohinta = new javax.swing.JTextField();
        uusiKate = new javax.swing.JTextField();
        uusiAlv = new javax.swing.JTextField();
        lisaaTarvike = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(799, 575));

        jLabel1.setText("Etunimi*");

        jLabel2.setText("Sukunimi*");

        osoiteLabel.setText("Osoite*");

        puhelinLabel.setText("Puhelin");

        jLabel5.setText("Sähköposti");

        lisaaAsiakasOK.setText("Lisää asiakas");
        lisaaAsiakasOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lisaaAsiakasOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(osoiteLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5)
                        .addComponent(puhelinLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lisaaAsiakasOK)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(uusiEtunimi)
                        .addComponent(uusiSahkoposti, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(uusiPuhelin)
                        .addComponent(uusiSukunimi)
                        .addComponent(uusiOsoite)))
                .addContainerGap(353, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uusiEtunimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uusiSukunimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uusiOsoite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(osoiteLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uusiPuhelin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puhelinLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(uusiSahkoposti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lisaaAsiakasOK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(237, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lisää asiakas", jPanel1);

        jScrollPane1.setViewportView(asiakasLista);

        jLabel3.setText("Asiakkaan nimi");

        haeAsiakkaat.setText("Hae");
        haeAsiakkaat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haeAsiakkaatActionPerformed(evt);
            }
        });

        kohteenTyyppi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "urakka", "tunti" }));

        jLabel4.setText("Tyyppi");

        kohteenOsoiteLabel.setText("Osoite");

        jLabel7.setText("Maksuerien lukumäärä");

        erienLKM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));

        lisaaKohdeOK.setText("Luo kohde");
        lisaaKohdeOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lisaaKohdeOKActionPerformed(evt);
            }
        });

        jLabel9.setText("Tarjous");

        onTarjous.setSelected(true);

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(kohteenOsoiteLabel)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(etsittavaAsiakas, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(haeAsiakkaat))
                                    .addComponent(kohteenTyyppi, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(163, 163, 163))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 415, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lisaaKohdeOK)
                                    .addComponent(jLabel26))
                                .addGap(88, 88, 88))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(kohteenOsoite)
                                        .addComponent(erienLKM, 0, 225, Short.MAX_VALUE))
                                    .addComponent(onTarjous)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(311, 311, 311)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(etsittavaAsiakas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(haeAsiakkaat))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kohteenTyyppi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kohteenOsoiteLabel)
                    .addComponent(kohteenOsoite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(erienLKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(onTarjous))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lisaaKohdeOK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("Lisää työkohde", jPanel2);

        etsittavaTarjous.setToolTipText("");

        jLabel8.setText("Hae tarjouksista");

        haeTarjouksista.setText("Hae");
        haeTarjouksista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haeTarjouksistaActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(tarjousLista);

        poistaTarjousStatus.setText("Tarjous hyväksytty");
        poistaTarjousStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poistaTarjousStatusActionPerformed(evt);
            }
        });

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText(" ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                        .addComponent(etsittavaTarjous)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(haeTarjouksista))))
                            .addComponent(poistaTarjousStatus)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(270, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etsittavaTarjous, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(haeTarjouksista))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(poistaTarjousStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addContainerGap(222, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Hallinnoi tarjouksia", jPanel7);

        jPanel3.setPreferredSize(new java.awt.Dimension(794, 520));

        jLabel10.setText("Kohteen osoite");

        haeKohdeOsoitteella.setText("Hae");
        haeKohdeOsoitteella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haeKohdeOsoitteellaActionPerformed(evt);
            }
        });

        kohdeLista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                kohdeListaValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(kohdeLista);

        jLabel11.setText("Lisää tunteja");

        tuntityyppi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "suunnittelu", "työ", "aputyö", "asennus" }));
        tuntityyppi.setToolTipText("");

        lisaaTuntejaOK.setText("Lisää");
        lisaaTuntejaOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lisaaTuntejaOKActionPerformed(evt);
            }
        });

        jLabel12.setText("Tarvikkeen nimi");

        haeTarvikeNimella.setText("Hae");
        haeTarvikeNimella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haeTarvikeNimellaActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(tarvikeLista);

        jLabel13.setText("Tarvikkeen määrä");

        lisaaTarvikeOK.setText("Lisää");
        lisaaTarvikeOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lisaaTarvikeOKActionPerformed(evt);
            }
        });

        kohdeSisaltaaTunnit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nimike", "Tunnit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(kohdeSisaltaaTunnit);
        if (kohdeSisaltaaTunnit.getColumnModel().getColumnCount() > 0) {
            kohdeSisaltaaTunnit.getColumnModel().getColumn(0).setMinWidth(130);
        }

        jLabel14.setText("Tuntien määrä");

        kohdeSisaltaaTarvikkeet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nimike", "Määrä", "Yksikkö"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(kohdeSisaltaaTarvikkeet);
        if (kohdeSisaltaaTarvikkeet.getColumnModel().getColumnCount() > 0) {
            kohdeSisaltaaTarvikkeet.getColumnModel().getColumn(0).setMinWidth(130);
        }

        jLabel27.setText("Tunnit");

        jLabel28.setText("Tarvikkeet");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(etsittavaTarvike, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(haeTarvikeNimella))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(tuntimaara)
                                                .addComponent(tuntityyppi, javax.swing.GroupLayout.Alignment.LEADING, 0, 200, Short.MAX_VALUE))
                                            .addComponent(etsittavaOsoite, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(haeKohdeOsoitteella)
                                            .addComponent(lisaaTuntejaOK)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(tarvikemaara, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lisaaTarvikeOK))
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel27))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel28)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(etsittavaOsoite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(haeKohdeOsoitteella)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel27)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tuntityyppi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tuntimaara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lisaaTuntejaOK)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etsittavaTarvike, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(haeTarvikeNimella))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tarvikemaara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(lisaaTarvikeOK)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68))
        );

        jTabbedPane1.addTab("Lisää veloituksia kohteeseen", jPanel3);

        jPanel4.setPreferredSize(new java.awt.Dimension(725, 573));

        jLabel15.setText("Kohteen osoite");

        jLabel16.setText("Asiakkaan nimi");

        paattyvaKohdeLista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                paattyvaKohdeListaValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(paattyvaKohdeLista);

        kohteenSisaltoTaulukko.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nimike", "Kappalehinta", "Määrä", "Alennus %", "Yhteensä"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        kohteenSisaltoTaulukko.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                kohteenSisaltoTaulukkoPropertyChange(evt);
            }
        });
        jScrollPane7.setViewportView(kohteenSisaltoTaulukko);

        haePaattyvaKohdeOsoite.setText("Hae");
        haePaattyvaKohdeOsoite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haePaattyvaKohdeOsoiteActionPerformed(evt);
            }
        });

        haePaattyvaKohdeAsiakas.setText("Hae");
        haePaattyvaKohdeAsiakas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haePaattyvaKohdeAsiakasActionPerformed(evt);
            }
        });

        luoLaskuOK.setText("Päätä työ ja luo lasku");
        luoLaskuOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luoLaskuOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(luoLaskuOK)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(78, 78, 78)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(75, 75, 75)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel15))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(paattyvaEtsittavaAsiakas, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(paattyvaEtsittavaOsoite))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(haePaattyvaKohdeOsoite)
                                                .addComponent(haePaattyvaKohdeAsiakas)))))))))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(paattyvaEtsittavaOsoite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(haePaattyvaKohdeOsoite))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(paattyvaEtsittavaAsiakas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(haePaattyvaKohdeAsiakas))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(luoLaskuOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Päätä kohde ja laskuta", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 778, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Luo karhukirjeet", jPanel5);

        jButton1.setText("Selaa..");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(346, 346, 346)
                .addComponent(jButton1)
                .addContainerGap(348, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jButton1)
                .addContainerGap(268, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Päivitä hinnasto", jPanel6);

        jLabel17.setText("Nimi*");

        jLabel18.setText("Yksikkö*");

        jLabel19.setText("Ostohinta*");

        jLabel20.setText("Varastotilanne*");

        jLabel21.setText("Kate (%)");

        jLabel22.setText("Alv (%)");

        uusiKate.setText("40");

        uusiAlv.setText("24");

        lisaaTarvike.setText("Lisää tarvike");
        lisaaTarvike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lisaaTarvikeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel21)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(uusiTarvikeNimi)
                            .addComponent(uusiYksikko)
                            .addComponent(uusiVarastotilanne)
                            .addComponent(uusiKate, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(uusiAlv)
                            .addComponent(uusiOstohinta)))
                    .addComponent(lisaaTarvike, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(441, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(uusiTarvikeNimi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(uusiYksikko, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(uusiVarastotilanne)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(uusiOstohinta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(uusiKate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(uusiAlv)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addComponent(lisaaTarvike)
                .addGap(48, 48, 48)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lisää tarvike", jPanel8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lisaaAsiakasOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lisaaAsiakasOKActionPerformed
        // TODO add your handling code here:
        if (uusiEtunimi.getText().isBlank() || uusiSukunimi.getText().isBlank()
                || uusiOsoite.getText().isBlank()) {
            jLabel6.setText("Täytithän kaikki vaaditut kentät.");
        } else {
            if (!uusiPuhelin.getText().isBlank()) {
                try {
                    int pnumero = Integer.parseInt(uusiPuhelin.getText());
                    String pnro = "" + pnumero;
                    if (uusiPuhelin.getText().charAt(0) == '0') {
                        pnro = "0" + pnumero;
                    }
                    jLabel6.setText("");
                    try {
                        dbmanager.lisaaAsiakas(uusiEtunimi.getText(), uusiSukunimi.getText(),
                                uusiOsoite.getText(), pnro, uusiSahkoposti.getText());
                        jLabel6.setText("Asiakas lisätty onnistuneesti.");
                        uusiEtunimi.setText("");
                        uusiSukunimi.setText("");
                        uusiOsoite.setText("");
                        uusiPuhelin.setText("");
                        uusiSahkoposti.setText("");
                    } catch (SQLException e) {
                        System.out.println(e.getMessage());
                        jLabel6.setText("Asiakkaan lisäys epäonnistui.");
                    }

                } catch (Exception e) {
                    jLabel6.setText("Virheellinen puhelinnumero!");
                }
            } else {
                try {
                    dbmanager.lisaaAsiakas(uusiEtunimi.getText(), uusiSukunimi.getText(),
                            uusiOsoite.getText(), uusiSahkoposti.getText());
                    jLabel6.setText("Asiakas lisätty onnistuneesti.");
                    uusiEtunimi.setText("");
                    uusiSukunimi.setText("");
                    uusiOsoite.setText("");
                    uusiSahkoposti.setText("");
                } catch (SQLException e) {
                    System.out.println(e.getMessage());
                    jLabel6.setText("Asiakkaan lisäys epäonnistui.");
                }
            }
        }
    }//GEN-LAST:event_lisaaAsiakasOKActionPerformed

    private void haeAsiakkaatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haeAsiakkaatActionPerformed
        DefaultListModel dlmAsiakas = new DefaultListModel();

        if (!etsittavaAsiakas.getText().isBlank()) {
            String[] osat = etsittavaAsiakas.getText().split(" ");
            if (osat.length == 1) {
                String nimi = osat[0].toLowerCase();
                try {
                    ArrayList<String> asiakkaat = dbmanager.haeAsiakkaat(nimi);
                    for (String asiakas : asiakkaat) {
                        dlmAsiakas.addElement(asiakas);
                    }
                } catch (SQLException e) {
                    System.out.println(e.getMessage());
                }
            } else if (osat.length == 2) {
                String enimi = osat[0].toLowerCase();
                String snimi = osat[1].toLowerCase();
                try {
                    ArrayList<String> asiakkaat = dbmanager.haeAsiakkaat(enimi, snimi);
                    for (String asiakas : asiakkaat) {
                        dlmAsiakas.addElement(asiakas);
                    }
                } catch (SQLException e) {
                    System.out.println(e.getMessage());
                }
            }
        } else {
            try {
                ArrayList<String> asiakkaat = dbmanager.haeAsiakkaat();
                for (String asiakas : asiakkaat) {
                    dlmAsiakas.addElement(asiakas);
                }
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
        }

        asiakasLista.setModel(dlmAsiakas);

    }//GEN-LAST:event_haeAsiakkaatActionPerformed

    private void lisaaKohdeOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lisaaKohdeOKActionPerformed
        // työkohteen luontilauseista puuttui tyypille vaihtoehto tarjous
        if (asiakasLista.getSelectedValue() == null
                || kohteenOsoite.getText().isBlank()
                || kohteenTyyppi.getSelectedItem().toString().isBlank()) {
            jLabel25.setText("Tarkista kentät!");

        } else {
            String asiakasid = asiakasLista.getSelectedValue().split(" ")[0];
            String tyyppi = kohteenTyyppi.getSelectedItem().toString();
            String osoite = kohteenOsoite.getText();
            String tarjous = Boolean.toString(onTarjous.isSelected());
            String eralkm = erienLKM.getSelectedItem().toString();
            try {
                dbmanager.lisaaKohde(asiakasid, tyyppi, tarjous, osoite, eralkm);
                jLabel25.setText("Työkohde lisätty onnistuneesti.");
                asiakasLista.setModel(new DefaultListModel());
                kohteenTyyppi.setSelectedIndex(0);
                kohteenOsoite.setText("");
                onTarjous.setSelected(false);
                erienLKM.setSelectedIndex(0);

            } catch (SQLException e) {
                System.out.println(e.getMessage());
                jLabel25.setText("Työkohteen lisäys epäonnistui.");
            }
        }

    }//GEN-LAST:event_lisaaKohdeOKActionPerformed

    private void poistaTarjousStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poistaTarjousStatusActionPerformed
        if (tarjousLista.getSelectedValue() == null) {
            jLabel24.setText("Valitse hyväksyttävä tarjous!");
        } else {
            try {
                String kohdeid = tarjousLista.getSelectedValue().split(" ")[0];
                dbmanager.hyvaksyTarjous(kohdeid);
                tarjousLista.setModel(new DefaultListModel());
                jLabel24.setText("Tarjous hyväksytty onnistuneesti.");
            } catch (SQLException e) {
                System.out.println(e.getMessage());
                jLabel24.setText("Tarjouksen hyväksyminen epäonnistui.");
            }
        }
    }//GEN-LAST:event_poistaTarjousStatusActionPerformed

    private void haeTarjouksistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haeTarjouksistaActionPerformed
        DefaultListModel dlmTarjous = new DefaultListModel();
        jLabel24.setText("");
        if (!etsittavaTarjous.getText().isBlank()) {
            String osoite = etsittavaTarjous.getText().toLowerCase();
            try {
                ArrayList<String> tarjoukset = dbmanager.haeTarjoukset(osoite);
                for (String tarjous : tarjoukset) {
                    dlmTarjous.addElement(tarjous);
                }
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
        } else {
            try {
                ArrayList<String> tarjoukset = dbmanager.haeTarjoukset();
                for (String tarjous : tarjoukset) {
                    dlmTarjous.addElement(tarjous);
                }
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }

        }

        tarjousLista.setModel(dlmTarjous);
    }//GEN-LAST:event_haeTarjouksistaActionPerformed

    private void lisaaTarvikeOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lisaaTarvikeOKActionPerformed
        if (tarvikeLista.getSelectedValue() == null
                || tarvikemaara.getText().isBlank()) {
            System.out.println("vituix män");
        } else {
            try {
                int maara = Integer.parseInt(tarvikemaara.getText());
                String kohdeid = kohdeLista.getSelectedValue().split(" ")[0];
                String nimi = tarvikeLista.getSelectedValue().split(" - ")[0];
                String lkm = "" + maara;
                dbmanager.lisaaKohteeseen(true, kohdeid, nimi, lkm);
                tarvikemaara.setText("");
                tarvikeLista.setSelectedValue(null, false);
                paivitaKohdeSisaltaaTaulukko(kohdeid);
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            } catch (Exception e) {
                System.out.println("vituix män ihan eri tavalla");
            }
        }
    }//GEN-LAST:event_lisaaTarvikeOKActionPerformed

    private void haeTarvikeNimellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haeTarvikeNimellaActionPerformed
        DefaultListModel dlmTarvike = new DefaultListModel();

        if (!etsittavaTarvike.getText().isBlank()) {
            String nimi = etsittavaTarvike.getText().toLowerCase();
            try {
                ArrayList<String> tarvikkeet = dbmanager.haeTarvikkeet(nimi);
                for (String tarvike : tarvikkeet) {
                    dlmTarvike.addElement(tarvike);
                }
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
        } else {
            try {
                ArrayList<String> tarvikkeet = dbmanager.haeTarvikkeet();
                for (String tarvike : tarvikkeet) {
                    dlmTarvike.addElement(tarvike);
                }
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
        }

        tarvikeLista.setModel(dlmTarvike);
    }//GEN-LAST:event_haeTarvikeNimellaActionPerformed

    private void lisaaTuntejaOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lisaaTuntejaOKActionPerformed
        if (kohdeLista.getSelectedValue() == null
                || tuntityyppi.getSelectedItem().toString().isBlank()
                || tuntimaara.getText().isBlank()) {
            System.out.println("vituix män");
        } else {
            try {
                float tunnit = Float.parseFloat(tuntimaara.getText());
                String lkm = "" + tunnit;
                String kohdeid = kohdeLista.getSelectedValue().split(" ")[0];
                String nimi = tuntityyppi.getSelectedItem().toString();
                dbmanager.lisaaKohteeseen(false, kohdeid, nimi, lkm);
                tuntityyppi.setSelectedIndex(0);
                tuntimaara.setText("");
                paivitaKohdeSisaltaaTaulukko(kohdeid);
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            } catch (Exception e) {
                System.out.println("vituix män ihan eri tavalla");
            }
        }
    }//GEN-LAST:event_lisaaTuntejaOKActionPerformed

    private void kohdeListaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_kohdeListaValueChanged
        if (!evt.getValueIsAdjusting() && kohdeLista.getSelectedValue() != null) {
            paivitaKohdeSisaltaaTaulukko(kohdeLista.getSelectedValue().split(" ")[0]);
        }
    }//GEN-LAST:event_kohdeListaValueChanged

    private void haeKohdeOsoitteellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haeKohdeOsoitteellaActionPerformed
        DefaultListModel dlmKohde = new DefaultListModel();

        if (!etsittavaOsoite.getText().isBlank()) {
            String osoite = etsittavaOsoite.getText().toLowerCase();
            try {
                ArrayList<String> kohteet = dbmanager.haeKohteetIlmanLaskua(osoite);
                for (String kohde : kohteet) {
                    dlmKohde.addElement(kohde);
                }
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
        } else {
            try {
                ArrayList<String> kohteet = dbmanager.haeKohteetIlmanLaskua();
                for (String kohde : kohteet) {
                    dlmKohde.addElement(kohde);
                }
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
        }
        kohdeLista.setModel(dlmKohde);
    }//GEN-LAST:event_haeKohdeOsoitteellaActionPerformed

    private void haePaattyvaKohdeOsoiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haePaattyvaKohdeOsoiteActionPerformed
        DefaultListModel dlmPaattyvaKohde = new DefaultListModel();

        if (!paattyvaEtsittavaOsoite.getText().isBlank()) {
            String osoite = paattyvaEtsittavaOsoite.getText().toLowerCase();
            try {
                ArrayList<String> kohteet = dbmanager.haeKohteet(osoite);
                for (String kohde : kohteet) {
                    dlmPaattyvaKohde.addElement(kohde);
                }
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
        } else {
            try {
                ArrayList<String> kohteet = dbmanager.haeKohteet();
                for (String kohde : kohteet) {
                    dlmPaattyvaKohde.addElement(kohde);
                }
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
        }

        paattyvaKohdeLista.setModel(dlmPaattyvaKohde);
    }//GEN-LAST:event_haePaattyvaKohdeOsoiteActionPerformed

    private void kohteenSisaltoTaulukkoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_kohteenSisaltoTaulukkoPropertyChange

        int col = kohteenSisaltoTaulukko.getEditingColumn();
        int row = kohteenSisaltoTaulukko.getEditingRow();

        if (row >= 0 && col >= 0) {
            try {
                // kokeillaan onko ale luku
                float ale = Float.parseFloat(kohteenSisaltoTaulukko.getValueAt(
                        row, col).toString());

                kohteenSisaltoTaulukko.setValueAt(
                        Float.parseFloat(kohteenSisaltoTaulukko.getValueAt(row, 1).toString())
                        * Float.parseFloat(kohteenSisaltoTaulukko.getValueAt(row, 2).toString())
                        * (100 - ale) / 100, row, 4);
                System.out.println("testi " + row + " " + col + " " + ale);
            } catch (Exception e) {
                // jos ale ei ole luku asetetaan arvoksi 0
                kohteenSisaltoTaulukko.setValueAt("0", row, col);
            }
        }
    }//GEN-LAST:event_kohteenSisaltoTaulukkoPropertyChange

    private void paattyvaKohdeListaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_paattyvaKohdeListaValueChanged
        if (!evt.getValueIsAdjusting()) {
            DefaultTableModel sisalto = (DefaultTableModel) kohteenSisaltoTaulukko.getModel();
            sisalto.addRow(new Object[]{"Tuntityö", 60, 5.7, 0, 5.7 * 60});
            sisalto.addRow(new Object[]{"Aputyö", 40, 4, 0, 4 * 40});
        }
    }//GEN-LAST:event_paattyvaKohdeListaValueChanged

    private void haePaattyvaKohdeAsiakasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haePaattyvaKohdeAsiakasActionPerformed
        DefaultListModel dlmPaattyvaKohde = new DefaultListModel();

        if (!paattyvaEtsittavaAsiakas.getText().isBlank()) {

            //??? kohteet = dbmanager.get
            //for kohde in kohteet {
            dlmPaattyvaKohde.addElement("0001 Kanslerinrinne 1, 33100 Tampere");
            //}
        }
        /* else {
            select * from tyokohde where tarjous = false
         */

        paattyvaKohdeLista.setModel(dlmPaattyvaKohde);
    }//GEN-LAST:event_haePaattyvaKohdeAsiakasActionPerformed

    private void luoLaskuOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luoLaskuOKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_luoLaskuOKActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        dbmanager.close();
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Select a file");
        int returnVal = fc.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();

            dbmanager.update(file);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lisaaTarvikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lisaaTarvikeActionPerformed
        if (uusiTarvikeNimi.getText().isBlank() || uusiYksikko.getText().isBlank() || uusiVarastotilanne.getText().isBlank() || uusiOstohinta.getText().isBlank()) {
            jLabel23.setText("Täytäs ny ne kaikki");
        } else {
            try {
                int vt = Integer.parseInt(uusiVarastotilanne.getText());
                double ohinta = Double.parseDouble(uusiOstohinta.getText());
                double kate = Double.parseDouble(uusiKate.getText());
                double alv = Double.parseDouble(uusiAlv.getText());
                dbmanager.lisaaTarvike(uusiTarvikeNimi.getText(), uusiYksikko.getText(), vt, ohinta, kate, alv);
                jLabel23.setText("Tarvikkeen lisäys onnistui.");
                uusiTarvikeNimi.setText("");
                uusiYksikko.setText("");
                uusiVarastotilanne.setText("");
                uusiOstohinta.setText("");
            } catch (SQLException e) {
                System.out.println(e.getMessage());
                jLabel23.setText("Tarvikkeen lisäys epäonnistui.");
            }
        }
    }//GEN-LAST:event_lisaaTarvikeActionPerformed

    private void initTaulukko() {
        kohdeSisaltaaTunnit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {}, new String [] {"Nimike", "Tunnit"}) {
            boolean[] canEdit = new boolean [] {false, false};
            
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(kohdeSisaltaaTunnit);
        if (kohdeSisaltaaTunnit.getColumnModel().getColumnCount() > 0) {
            kohdeSisaltaaTunnit.getColumnModel().getColumn(0).setMinWidth(130);
        }
        kohdeSisaltaaTarvikkeet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {}, new String [] {"Nimike", "Määrä", "Yksikkö"}) {
            boolean[] canEdit = new boolean [] {false, false, false};

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(kohdeSisaltaaTarvikkeet);
        if (kohdeSisaltaaTarvikkeet.getColumnModel().getColumnCount() > 0) {
            kohdeSisaltaaTarvikkeet.getColumnModel().getColumn(0).setMinWidth(130);
        }
    }
    
    private void paivitaKohdeSisaltaaTaulukko(String id) {
        initTaulukko();
        DefaultTableModel tunnit = (DefaultTableModel) kohdeSisaltaaTunnit.getModel();
        DefaultTableModel tarvikkeet = (DefaultTableModel) kohdeSisaltaaTarvikkeet.getModel();

        try {
            ArrayList<String> kohteenTunnit = dbmanager.haeKohteenTunnit(id);
            ArrayList<String> kohteenTarvikkeet = dbmanager.haeKohteenTarvikkeet(id);
            for (String tuntityyppi : kohteenTunnit) {
                String nimike = tuntityyppi.split("::")[0];
                double maara = Double.parseDouble(tuntityyppi.split("::")[1]);
                nimike = nimike.substring(0, 1).toUpperCase() + nimike.substring(1);
                // System.out.println(nimike.replace('o', 'ö'));
                tunnit.addRow(new Object[]{nimike, maara});
            }
            for (String tarvike : kohteenTarvikkeet) {
                String nimike = tarvike.split("::")[0];
                String yksikko = tarvike.split("::")[1];
                int maara = Integer.parseInt(tarvike.split("::")[2]);
                tarvikkeet.addRow(new Object[]{nimike, maara, yksikko});
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> asiakasLista;
    private javax.swing.JComboBox<String> erienLKM;
    private javax.swing.JTextField etsittavaAsiakas;
    private javax.swing.JTextField etsittavaOsoite;
    private javax.swing.JTextField etsittavaTarjous;
    private javax.swing.JTextField etsittavaTarvike;
    private javax.swing.JButton haeAsiakkaat;
    private javax.swing.JButton haeKohdeOsoitteella;
    private javax.swing.JButton haePaattyvaKohdeAsiakas;
    private javax.swing.JButton haePaattyvaKohdeOsoite;
    private javax.swing.JButton haeTarjouksista;
    private javax.swing.JButton haeTarvikeNimella;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> kohdeLista;
    private javax.swing.JTable kohdeSisaltaaTarvikkeet;
    private javax.swing.JTable kohdeSisaltaaTunnit;
    private javax.swing.JTextField kohteenOsoite;
    private javax.swing.JLabel kohteenOsoiteLabel;
    private javax.swing.JTable kohteenSisaltoTaulukko;
    private javax.swing.JComboBox<String> kohteenTyyppi;
    private javax.swing.JButton lisaaAsiakasOK;
    private javax.swing.JButton lisaaKohdeOK;
    private javax.swing.JButton lisaaTarvike;
    private javax.swing.JButton lisaaTarvikeOK;
    private javax.swing.JButton lisaaTuntejaOK;
    private javax.swing.JButton luoLaskuOK;
    private javax.swing.JCheckBox onTarjous;
    private javax.swing.JLabel osoiteLabel;
    private javax.swing.JTextField paattyvaEtsittavaAsiakas;
    private javax.swing.JTextField paattyvaEtsittavaOsoite;
    private javax.swing.JList<String> paattyvaKohdeLista;
    private javax.swing.JButton poistaTarjousStatus;
    private javax.swing.JLabel puhelinLabel;
    private javax.swing.JList<String> tarjousLista;
    private javax.swing.JList<String> tarvikeLista;
    private javax.swing.JTextField tarvikemaara;
    private javax.swing.JTextField tuntimaara;
    private javax.swing.JComboBox<String> tuntityyppi;
    private javax.swing.JTextField uusiAlv;
    private javax.swing.JTextField uusiEtunimi;
    private javax.swing.JTextField uusiKate;
    private javax.swing.JTextField uusiOsoite;
    private javax.swing.JTextField uusiOstohinta;
    private javax.swing.JTextField uusiPuhelin;
    private javax.swing.JTextField uusiSahkoposti;
    private javax.swing.JTextField uusiSukunimi;
    private javax.swing.JTextField uusiTarvikeNimi;
    private javax.swing.JTextField uusiVarastotilanne;
    private javax.swing.JTextField uusiYksikko;
    // End of variables declaration//GEN-END:variables
}
